# Generated by Django 3.2.8 on 2023-05-02 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_gallerypost'),
        ('chatroom', '0002_alter_room_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.organization'),
        ),
        migrations.AddField(
            model_name='message',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.volunteer'),
        ),
    ]
