# Generated by Django 4.1.7 on 2023-02-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=256)),
                ('job_pubdate', models.DateTimeField(verbose_name='date published')),
                ('job_discription', models.CharField(max_length=1024)),
                ('job_location', models.CharField(max_length=256)),
                ('job_worktime', models.CharField(default='Not Specified', max_length=256)),
                ('job_image', models.CharField(max_length=256)),
                ('job_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_profile.organization')),
            ],
        ),
    ]
