# Generated by Django 3.2.8 on 2023-03-24 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("opportunityboard", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.organization",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opportunityboard.subcategory",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="subsubcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opportunityboard.subsubcategory",
            ),
        ),
    ]
