# Generated by Django 3.2.8 on 2023-03-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunityboard", "0002_job_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="category",
            field=models.CharField(
                choices=[
                    ("sports", "Sports"),
                    ("animals", "Animal"),
                    ("community", "Community"),
                    ("environment", "Environment"),
                    ("healthcare", "Healthcare"),
                ],
                max_length=20,
            ),
        ),
    ]
