# Generated by Django 3.2.8 on 2023-03-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0002_auto_20230317_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='subcategory_1',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='subcategory_2',
            new_name='subsubcategory',
        ),
    ]
