# Generated by Django 3.2.8 on 2023-04-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='is_archive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
