# Generated by Django 4.0 on 2023-03-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0002_opportunity_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('healthcare', 'Healthcare'), ('community', 'Community'), ('environment', 'Environment'), ('animals', 'Animal'), ('sports', 'Sports')], max_length=20),
        ),
    ]
