# Generated by Django 4.1.7 on 2023-03-30 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("opportunityboard", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.volunteer",
            ),
        ),
    ]
