# Generated by Django 3.2.8 on 2023-03-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0002_opportunity_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('healthcare', 'Healthcare'), ('animals', 'Animal'), ('sports', 'Sports'), ('community', 'Community'), ('environment', 'Environment')], max_length=20),
        ),
    ]
