# Generated by Django 3.2.8 on 2023-03-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunityboard", "0003_alter_opportunity_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="pubdate",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
