# Generated by Django 3.2.8 on 2023-03-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0004_auto_20230318_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubcategory',
            name='grandparent',
        ),
    ]
