# Generated by Django 3.2.8 on 2023-03-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0002_opportunity_organization'),
        ('opportunityboard', '0006_auto_20230319_0327'),
    ]

    operations = [
    ]
