# Generated by Django 4.1.7 on 2023-03-30 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunityboard", "0006_remove_opportunity_volunteer_opportunity_volunteer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="volunteer",
        ),
    ]
