# Generated by Django 3.2.8 on 2023-03-26 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunityboard", "0006_rename_frequency_opportunity_recurrence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="occurences",
        ),
    ]
