# Generated by Django 4.0 on 2023-03-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0003_alter_opportunity_category'),
        ('opportunityboard', '0009_alter_opportunity_staffing'),
    ]

    operations = [
    ]
