# Generated by Django 4.1.7 on 2023-03-30 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunityboard", "0007_remove_opportunity_occurences"),
        ("opportunityboard", "0011_remove_opportunity_volunteer_opportunity_volunteer"),
    ]

    operations = []
