# Generated by Django 3.2.8 on 2023-04-02 16:36

import opportunityboard.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunityboard", "0013_alter_opportunity_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=opportunityboard.models._opportunity_photo_path,
            ),
        ),
    ]
