# Generated by Django 3.2.8 on 2023-04-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_alter_volunteer_hours_volunteered"),
        ("opportunityboard", "0016_rename_volunteer_opportunity_volunteers"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="attended_volunteers",
            field=models.ManyToManyField(
                blank=True, related_name="attended_volunteers", to="profiles.Volunteer"
            ),
        ),
    ]
