# Generated by Django 3.2.8 on 2023-04-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0017_opportunity_attended_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
