# Generated by Django 3.2.8 on 2023-04-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0018_opportunity_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='recurrence_siblings',
            field=models.ManyToManyField(blank=True, null=True, to='opportunityboard.Opportunity'),
        ),
    ]
