# Generated by Django 3.2.8 on 2023-05-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunityboard', '0019_opportunity_recurrence_siblings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
