# Generated by Django 3.2.8 on 2023-05-06 23:18

import datetime

from django.db import migrations, models


def UpdateTime(apps, schema_editor):
    Opportunity = apps.get_model("opportunityboard", "Opportunity")
    for opp in Opportunity.objects.all():
        opp.end = datetime.datetime.combine(opp.date, opp.end.time())
        opp.save()


class Migration(migrations.Migration):

    dependencies = [
        ("opportunityboard", "0020_auto_20230506_1845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="end",
            field=models.DateTimeField(),
        ),
        migrations.RunPython(UpdateTime),
    ]
