# Generated by Django 4.1.7 on 2023-02-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('organization', 'Organization'), ('admin', 'Admin')], default='volunteer', max_length=12),
        ),
    ]
