# Generated by Django 4.1.7 on 2023-02-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('organization', 'Organization')], default='volunteer', max_length=12),
        ),
    ]
