# Generated by Django 4.0 on 2023-03-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nycharities',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nycharities',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
