# Generated by Django 4.0 on 2023-03-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_nycharities_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nycharities',
            name='bin_num',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
