# Generated by Django 4.0 on 2023-03-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_nycharities_latitude_nycharities_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nycharities',
            options={'verbose_name_plural': 'nycharities'},
        ),
    ]
