# Generated by Django 3.2.8 on 2023-04-10 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='hours_volunteered',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
