# Generated by Django 4.1.7 on 2023-03-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="images/default-profile-pic.png", upload_to="images/"
            ),
        ),
    ]
