# Generated by Django 3.2.8 on 2023-03-25 21:15

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models._profile_photo_path),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models._profile_photo_path),
        ),
    ]
