# Generated by Django 4.1.7 on 2023-03-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="photo",
            field=models.ImageField(
                default="default-profile-pic.png", upload_to="media/"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="photo",
            field=models.ImageField(
                default="default-profile-pic.png", upload_to="media/"
            ),
        ),
    ]
