# Generated by Django 3.2.8 on 2023-03-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(default='', help_text='Introduce your organization here.'),
        ),
    ]
