# Generated by Django 3.2.8 on 2023-03-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="photo",
            field=models.ImageField(
                blank=True, default="images/user-0.png", upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="photo",
            field=models.ImageField(
                blank=True, default="images/user-0.png", upload_to="images/"
            ),
        ),
    ]
