# Generated by Django 4.1.7 on 2023-03-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="photo",
            field=models.ImageField(
                default="images/default-profile-pic.png", upload_to="images/"
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="photo",
            field=models.ImageField(
                default="images/default-profile-pic.png", upload_to="images/"
            ),
        ),
    ]
