# Generated by Django 4.1.7 on 2023-03-13 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_organization_photo_alter_volunteer_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
