# Generated by Django 3.2.8 on 2023-04-06 00:53
import datetime

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_auto_20230325_2115"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200)),
                ("type", models.IntegerField(choices=[(0, "Hours Volunteered")])),
                ("img", models.ImageField(upload_to=profiles.models._badge_img_path)),
                ("hours_required", models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name="volunteer",
            name="hours_volunteered",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
