# Generated by Django 3.2.8 on 2023-04-08 16:35

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_auto_20230408_1113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="img",
            field=models.ImageField(upload_to=profiles.models._badge_img_path),
        ),
    ]
