# Generated by Django 3.2.8 on 2023-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_alter_badge_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="type",
            field=models.IntegerField(choices=[(0, "VOLUNTEER_HOURS_BADGE")]),
        ),
    ]
