# Generated by Django 4.1.7 on 2023-03-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("pubdate", models.DateTimeField(verbose_name="date published")),
                ("description", models.CharField(max_length=1024)),
                ("location", models.CharField(max_length=256)),
                ("worktime", models.CharField(default="Not Specified", max_length=256)),
                ("image", models.CharField(max_length=256)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.organization",
                    ),
                ),
            ],
        ),
    ]
