# Generated by Django 4.1.7 on 2023-03-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
