# Generated by Django 4.1.7 on 2023-03-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("litter collection", "Litter Collection"),
                    ("clothing drive", "Clothing Drive"),
                    ("soup kitchen", "Soup Kitchen"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="pubdate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
