# Generated by Django 4.1.7 on 2023-03-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobboard", "0002_alter_job_address_alter_job_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothing drive", "Clothing Drive"),
                    ("soup kitchen", "Soup Kitchen"),
                    ("litter collection", "Litter Collection"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="pubdate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
