# Generated by Django 4.1.7 on 2023-03-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobboard", "0004_alter_job_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="address",
            new_name="address_1",
        ),
        migrations.AddField(
            model_name="job",
            name="address_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("sports", "Sports"),
                    ("community", "Community"),
                    ("environment", "Environment"),
                    ("healthcare", "Healthcare"),
                    ("animals", "Animal"),
                ],
                max_length=20,
            ),
        ),
    ]
