# Generated by Django 3.2.8 on 2023-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0005_rename_address_job_address_1_job_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('healthcare', 'Healthcare'), ('environment', 'Environment'), ('community', 'Community'), ('animals', 'Animal'), ('sports', 'Sports')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
