# Generated by Django 3.2.8 on 2023-03-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0006_auto_20230311_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('healthcare', 'Healthcare'), ('animals', 'Animal'), ('environment', 'Environment'), ('community', 'Community')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='staffing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
