# Generated by Django 4.1.5 on 2023-02-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=256)),
                ('organization_email', models.CharField(default='', max_length=256)),
                ('organization_address_city', models.CharField(default='', max_length=256)),
                ('organization_image', models.CharField(default='images/organize_image_unknown.png', max_length=256)),
                ('organization_website', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
