# Generated by Django 4.1.5 on 2023-02-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('user_email', models.CharField(max_length=256)),
                ('user_address_city', models.CharField(max_length=256)),
                ('user_address_zipcode', models.IntegerField()),
                ('user_skill', models.CharField(default='', max_length=1024)),
                ('user_badges', models.CharField(default='', max_length=1024)),
                ('user_preference', models.CharField(default='', max_length=1024)),
                ('user_image', models.CharField(max_length=256)),
            ],
        ),
    ]
