# Generated by Django 4.1.5 on 2023-01-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('job_discription', models.CharField(max_length=1024)),
                ('work_location', models.CharField(max_length=256)),
                ('work_time', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
