# Generated by Django 4.1.5 on 2023-02-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluncheer', '0002_user_rename_work_location_job_job_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_badges',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='user_preference',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='user_skill',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
