# Generated by Django 4.1.5 on 2023-02-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluncheer', '0003_user_user_badges_user_user_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
