# Generated by Django 4.1.5 on 2023-02-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluncheer', '0004_remove_job_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_address_city',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_image',
            field=models.CharField(default='images/organize_image_unknown.png', max_length=256),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_website',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluncheer.organization'),
        ),
    ]
