name: Prepare Python Environment
description: Prepares the environment with Python and PyPy dependencies
inputs:
  python-version:
    default: "3.7"
    description: The version of Python to install
    required: false
runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
    - name: Install Dependencies
      shell: bash
      working-directory: voluncheer
      run: pip install -r requirements.txt
    - name: Database Migrations
      shell: bash
      working-directory: voluncheer
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: spin up redis with docker
      shell: bash
      working-directory: voluncheer
      run: |
        docker run -p 6379:6379 -d redis:5